; (require 'jl-evil)
; (require 'jl-ido)
(require 'jl-helm)
(require 'jl-guide-key)
(require 'jl-yasnippet)
(require 'jl-projectile)
(require 'jl-ace-jump)
(require 'jl-web-mode)
(require 'jl-coffee-mode)
(require 'jl-js-mode)
(require 'jl-emmet-mode)
(require 'jl-magit)
(require 'jl-sh-mode)
(require 'jl-hungry-delete)
(require 'jl-diminish)
(require 'jl-git-gutter-fringe)
(require 'jl-visual-regexp)
(require 'jl-expand-region)
(require 'jl-multiple-cursors)
(require 'jl-smartscan)
(require 'jl-company)
(require 'jl-dired)
(require 'jl-swiper)
