; (require 'jl-evil)
(require 'jl-guide-key)
(require 'jl-yasnippet)
(require 'jl-projectile)
(require 'jl-ido)
(require 'jl-ace-jump)
(require 'jl-web-mode)
(require 'jl-js-mode)
(require 'jl-emmet-mode)
(require 'jl-magit)
(require 'jl-sh-mode)
