alias kc="source <(kubectl completion zsh)"
alias k="kubectl"
alias kp="kubectl proxy"
alias kl="kubectl logs"
alias kex="kubectl exec"
alias kexti="kubectl exec -ti"
alias ksd="kubectl scale deployment"

alias kgp="kubectl get pods"
alias kgpag="kubectl get pods | ag"
alias kgd="kubectl get deployments"
alias kgi="kubectl get ingresses"
alias kgn="kubectl get nodes"
alias kgrs="kubectl get replicasets"
alias kgs="kubectl get secrets"
alias kgj="kubectl get jobs"
alias kgss="kubectl get statefulsets"

alias kdp="kubectl describe pods"
alias kdd="kubectl describe deployments"
alias kdi="kubectl describe ingresses"
alias kdn="kubectl describe nodes"
alias kdrs="kubectl describe replicasets"
alias kds="kubectl describe secrets"
alias kdj="kubectl describe jobs"
alias kdss="kubectl describe statefulsets"

alias kep="kubectl edit pod"
alias ked="kubectl edit deployment"
alias kei="kubectl edit ingress"
alias kers="kubectl edit replicaset"
alias kej="kubectl edit job"
alias kess="kubectl edit statefulset"

alias kdep="kubectl delete pod"
alias kded="kubectl delete deployment"
alias kdei="kubectl delete ingress"
alias kders="kubectl delete replicaset"
alias kdej="kubectl delete job"
alias kdess="kubectl delete statefulset"
