set nocompatible
" LEADERS {{{
  let mapleader=','
  let maplocalleader = "\\"
" }}}

" SET UP vim-plug {{{
  source ~/.vim/vim-plug.vim
" }}}
filetype plugin indent on

" at top to ensure functions are defined before use
" UTILITY FUNCTIONS {{{
  source ~/.vim/utilities.vim
" }}}

" ABBREVIATIONS {{{
  source ~/.vim/abbreviations.vim
" }}}
