(source gnu)
(source melpa)

;; package management
(depends-on "pallet")

;; language modes
(depends-on "clojure-mode")
(depends-on "coffee-mode")
(depends-on "css-mode")
(depends-on "markdown-mode")
(depends-on "ruby-mode")
(depends-on "scss-mode")
(depends-on "web-mode")
(depends-on "js2-mode")
(depends-on "emmet-mode")

;; searching
(depends-on "flx-ido")
(depends-on "ido-ubiquitous")
(depends-on "smex")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-projectile")
(depends-on "helm-descbinds")
(depends-on "visual-regexp")

;; vim/modal editing
(depends-on "evil")
(depends-on "evil-leader")

;; quick jumping
(depends-on "ace-jump-mode")
(depends-on "ace-jump-buffer")
(depends-on "ace-window")
(depends-on "smartscan")

;; ui
(depends-on "diminish")
(depends-on "zenburn-theme")

;; git
(depends-on "magit")
(depends-on "git-gutter-fringe")

;; text manipulation
(depends-on "expand-region")
(depends-on "hungry-delete")
(depends-on "smartparens")
(depends-on "multiple-cursors")

;; utilities
(depends-on "flycheck")
(depends-on "guide-key")
(depends-on "projectile")
(depends-on "yasnippet")
