(source gnu)
(source melpa)

;; package management
(depends-on "pallet")

;; language modes
(depends-on "clojure-mode")
(depends-on "coffee-mode")
(depends-on "css-mode")
(depends-on "markdown-mode")
(depends-on "ruby-mode")
(depends-on "scss-mode")

;; searching
(depends-on "flx-ido")
(depends-on "ido-ubiquitous")
(depends-on "smex")

;; vim/modal editing
(depends-on "evil")
(depends-on "evil-leader")

;; quick jumping
(depends-on "ace-jump-mode")
(depends-on "ace-jump-buffer")

;; utilities
(depends-on "flycheck")
(depends-on "guide-key")
(depends-on "magit")
(depends-on "projectile")
(depends-on "smartparens")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
