#!/bin/sh

# exit if any subshell or command exits with a nonzero status
set -e

echo "Setting up dependencies..."

cd "$( dirname $0 )"/..

# find the setup and run them iteratively
find . -name setup*.sh | sort | while read setup ; do sh "${setup}" ; done

echo "Installing scripts..."

# find the installers and run them iteratively
find . -name install*.sh | while read installer ; do sh "${installer}" ; done

echo "Finished installing scripts"
