skip_global_compinit=1

typeset -U path

# Favor Homebrew binaries over system
path=($HOME/.yarn/bin $HOME/.cargo/env ./yarn/bin ./node_modules/.bin /usr/local/bin /usr/local/sbin $GOPATH/bin $GOROOT/bin $path)
